// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      //Added to github
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGYdwgUk0bgHbzZfD_9UGzUoXOjerC60',
    appId: '1:753026110692:web:63cc6890d4e6651341c8f1',
    messagingSenderId: '753026110692',
    projectId: 'serenessa-5242a',
    authDomain: 'serenessa-5242a.firebaseapp.com',
    storageBucket: 'serenessa-5242a.firebasestorage.app',
    measurementId: 'G-0JB79NKL31',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj7sZGwcW3aedyWIy1yA1S4PYU2FxfIT4',
    appId: '1:753026110692:ios:63344e2e9a7acadc41c8f1',
    messagingSenderId: '753026110692',
    projectId: 'serenessa-5242a',
    storageBucket: 'serenessa-5242a.firebasestorage.app',
    iosBundleId: 'com.example.serenessaFirstVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj7sZGwcW3aedyWIy1yA1S4PYU2FxfIT4',
    appId: '1:753026110692:ios:63344e2e9a7acadc41c8f1',
    messagingSenderId: '753026110692',
    projectId: 'serenessa-5242a',
    storageBucket: 'serenessa-5242a.firebasestorage.app',
    iosBundleId: 'com.example.serenessaFirstVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDGYdwgUk0bgHbzZfD_9UGzUoXOjerC60',
    appId: '1:753026110692:web:587ba2ded9b462ec41c8f1',
    messagingSenderId: '753026110692',
    projectId: 'serenessa-5242a',
    authDomain: 'serenessa-5242a.firebaseapp.com',
    storageBucket: 'serenessa-5242a.firebasestorage.app',
    measurementId: 'G-H0JWDLW3BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wv2eOUpMeCS76OM8yNLpdVUTfbGnRro',
    appId: '1:753026110692:android:bf439d1b691e2da241c8f1',
    messagingSenderId: '753026110692',
    projectId: 'serenessa-5242a',
    storageBucket: 'serenessa-5242a.firebasestorage.app',
  );

}